import org.apache.spark.sql.types.{ArrayType, DoubleType, MapType, StringType, StructType}

object SchemaData {

  val inputJsonSchema = new StructType()
    .add("Deequ", new StructType().add("Analysers", ArrayType(new StructType()
      .add("function",StringType,nullable = true)
      .add("columnName",StringType,nullable = true)
      .add("condition",StringType,nullable = true))
    )
    .add("Checks", ArrayType(new StructType()
      .add("checkName",StringType,nullable = true)
      .add("function",StringType,nullable = true)
      .add("columnName",StringType,nullable = true)
      .add("params",StringType,nullable = true)
      .add("multipleColumns",StringType,nullable = true)
    )))
    .add("Source",new StructType()
      .add("Path",StringType)
      .add("Format",StringType))
    .add("Destination",new StructType()
      .add("Path",StringType)
      .add("Format",StringType))

  val sysAuditSchema = new StructType().add("objectClass", StringType,nullable = true)
//    .add("objectId", StringType,nullable = true)
    .add("sysEndPointMethod",StringType,nullable = true)
    .add("sysEndPointURI",StringType,nullable = true)
    .add("sysEndPointVersion",StringType,nullable = true)
    .add("sysRequestReference",StringType,nullable = true)
    .add("sysTxDateStamp",StringType,nullable = true)

  val sourceAccountSchema = new StructType()
    .add("accountId", StringType,nullable = true)
    .add("agreementComponentId",StringType,nullable = true)
    .add("agreementNumber",StringType,nullable = true)
    .add("coverageId",StringType,nullable = true)
    .add("objectClass",StringType,nullable = true)
    .add("walletAddress",StringType,nullable = true)

  val basePremiumModifierSchema = ArrayType(new StructType()
    .add("objectClass",StringType,nullable = true)
    .add("premiumModifierExcess",StringType,nullable = true)
    .add("premiumModifierName",StringType,nullable = true)
    .add("premiumModifierPerc",StringType,nullable = true))

  val coverageDetailSchema = ArrayType(new StructType()
    .add("name",StringType,nullable = true)
    .add("level",StringType,nullable = true)
    .add("basePremiumRate",StringType,nullable = true)
    .add("basePremiumRateTableRowId",StringType,nullable = true))

  val investmentOptionSchema = new StructType()
    .add("allocation", MapType(StringType, DoubleType),nullable = true)
    .add("amount",StringType,nullable = true)
    .add("objectClass",StringType,nullable = true)
    .add("type",StringType,nullable = true)

  val pendingTransactionSchema = ArrayType(new StructType()
    .add("amount",StringType,nullable = true)
    .add("date",StringType,nullable = true)
    .add("objectClass",StringType,nullable = true)
    .add("sourceAccountId",StringType,nullable = true)
    .add("type",StringType,nullable = true)
    .add("units",StringType,nullable = true))

  val payloadSchema = new StructType()
    .add("agreementHolder", StringType,nullable = true)
    .add("agreementNumber", StringType,nullable = true)
    .add("agreementStatus", StringType,nullable = true)
    .add("accountId",StringType,nullable = true)
    .add("accountName",StringType,nullable = true)
    .add("inceptionDate", StringType,nullable = true)
    .add("issueDate", StringType,nullable = true)
    .add("country", StringType,nullable = true)
    .add("currencyCode", StringType,nullable = true)
    .add("objectId", StringType,nullable = true)
    .add("objectClass", StringType,nullable = true)
    .add("coverageId", StringType,nullable = true)
    .add("agreementComponentId", StringType,nullable = true)
    .add("agreementComponentStatus", StringType,nullable = true)
    .add("effectiveEndDate", StringType,nullable = true)
    .add("autoRenew",StringType,nullable = true)
    .add("isRider",StringType,nullable = true)
    .add("riderRef",StringType,nullable = true)
    .add("noClaimDiscountRate",StringType,nullable = true)
    .add("basePremiumModifiers", basePremiumModifierSchema)
    .add("investmentOptions", investmentOptionSchema)
    .add("billingMethod",StringType,nullable = true)
    .add("noClaimDiscountApplied",StringType,nullable = true)
    .add("coverages" ,coverageDetailSchema)
    .add("coverageStatuses",ArrayType(StringType))
    .add("balance",StringType,nullable = true)
    .add("billingMode",StringType,nullable = true)
    .add("basePremiumAmount",StringType,nullable = true)
    .add("basePremiumRate",StringType,nullable = true)
    .add("basePremiumRateTableRowId",StringType,nullable = true)
    .add("faceAmount",StringType,nullable = true)
    .add("finalPremiumAmount",StringType,nullable = true)
    .add("transactionDate",StringType,nullable = true)
    .add("transactionType",StringType,nullable = true)
    .add("transactionValue",StringType,nullable = true)
    .add("fundId",StringType,nullable = true)
    .add("fundPrice",StringType,nullable = true)
    .add("id",StringType,nullable = true)
    .add("status",StringType,nullable = true)
    .add("taxRate",StringType,nullable = true)
    .add("asset", StringType,nullable = true)
    .add("sysAudit", sysAuditSchema)
    .add("sourceAccount", sourceAccountSchema)
    .add("contacts", new StructType().add("contact", ArrayType(new StructType()
      .add("contactId",StringType,nullable = true)
      .add("crmId",StringType,nullable = true)
      .add("contactType",StringType,nullable = true)
      .add("dateOfBirth",StringType,nullable = true)
      .add("gender",StringType,nullable = true)
      .add("objectClass",StringType,nullable = true))))
    .add("pendingTransactions",pendingTransactionSchema)
    .add("underwritingParameters", MapType(StringType,StringType) ,nullable = true)
    .add("walletAddress",StringType,nullable = true)

  val jsonSourceSchema = new StructType()
    .add("address",StringType,nullable = true)
    .add("transactionId",StringType,nullable = true)
    .add("payload", payloadSchema)
    .add("contextId",StringType,nullable = true)
    .add("telemetry",StringType,nullable = true)



}
